### PR TITLE
Update Italian translation

### PR DESCRIPTION
**Pull request by airon90**
I fixed all Italian translations making them uniform and more user friendly. I fixed some parts which weren't translated and I fixed all titles

## Summary by CodeRabbit

- **New Features**
	- Enhanced Italian localization across various scripts for improved clarity and user engagement.
	- Titles and phrases have been updated for a more direct and personal tone, making the installation process more relatable.

- **Bug Fixes**
	- Corrected grammatical errors and improved readability in Italian localization strings.

- **Documentation**
	- Updated installation messages and prompts to better reflect the intended user experience in Italian.

- **Chores**
	- Standardized terminology and phrasing throughout the localization files for consistency.

### CODE REVIEW

**Review by goldyfruit — APPROVED** [review]

**Comment by goldyfruit** [comment]
@airon90 is the PR ready to be review of does the draft mode is on purpose?

**Comment by airon90** [comment]
> @airon90 is the PR ready to be review of does the draft mode is on purpose?

I don't know whether I can finish working on it this evening or tomorrow.

**Comment by airon90** [comment]
@goldyfruit I finished fixing translations. Please tell me if I missed some parts

**Review by goldyfruit — APPROVED** [review]

**Comment by goldyfruit** [comment]
Thanks @airon90 :+1:

**Pull request merged**
