### PR TITLE
feat/arch_support

### LINKED ISSUE #58: Support for Manjaro/Arch/Endeavour
Operating systemd not supported.
I want to use ovos on my EndeavourOS machine, as I did with mycroft before it was shut down

### PR DESCRIPTION
**Pull request by JarbasAl**
still untested, need to verify all package names!

closes #58

### CODE REVIEW

**Comment by JarbasAl** [comment]
image
image

test with venv / containers both install and uninstall with all combos of hivemind/ovos/gui 

only didnt test voice sat

**Review by builderjer — APPROVED** [review]
This seems to work well for me.  I tested installation into a venv with a gui and had no errors.

I few things with the installer in general
- I would like to be able to pick where my venv is
- It moves my existing `~/.config/mycroft/mycroft.conf` instead of using it, or at least asking to use it
- it also wrote over my existing systemd files and I don't like that.  Either use them, or ask to overwrite, or something

Overall, this works as intended, just not like I would like

**Comment by goldyfruit** [comment]
> * I would like to be able to pick where my venv is

Many people doesn't know what a venv, this is prone to user error.

> * It moves my existing `~/.config/mycroft/mycroft.conf` instead of using it, or at least asking to use it

We discussed this point on Matrix, if the user change the `mcyroft.conf` then the installer backups the file _(in `~/.config/mycroft/`)_ but restore the original to avoid user's breaking change.

> * it also wrote over my existing systemd files and I don't like that.  Either use them, or ask to overwrite, or something
99% of the user will not have existing `ovos-*.service` in `~/.config/systemd/user/` directory. The installer will not use existing files as they might be totally different of what the installer is expecting.

**Comment by JarbasAl** [comment]
> * t also wrote over my existing systemd files and I don't like that.  Either use them, or ask to overwrite, or something

IMHO this is intended, if its doing a reinstall on top of an existing one most likely something is broken or outdated, and if the user then runs this installer on top then that is what gets the user back into a working state.

people who made their own service files either know what they are doing and dont want to use installer at all, or are noobs who followed some script or advice they didnt understand and now dont have a working ovos install

**Comment by goldyfruit** [comment]
> I agree with these, especially the venv. But if there are existing files, the user must know they are there, so there should at least be a prompt or verification that they are getting moved/overwritten

Just added a backup option, if files exist and there is a change in it then the file will be backup.

https://github.com/OpenVoiceOS/ovos-installer/commit/0505c2ed01e26d0d88f9cbda86f93b89c6a09bf6

**Review by goldyfruit — APPROVED** [review]

**Pull request merged**
